version: "3.7"
services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    command:
      - --encryptionEnv #optional
      - ENCRYPTION #optional
    environment:
      ENCRYPTION: example #optional
    ports:
      - "8090:8090"
    volumes:
      - /home/docker/pocketbase/pb_data:/pb_data
      - /home/docker/pocketbase/pb_public:/pb_public #optional
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
  speedtest:
      container_name: speedtest
      image: henrywhitaker3/speedtest-tracker
      ports:
          - 8765:80
      volumes:
          - /home/docker/speedtest/config:/config
      environment:
          - TZ=
          - PGID=
          - PUID=
          - OOKLA_EULA_GDPR=true
      logging:
          driver: "json-file"
          options:
              max-file: "10"
              max-size: "200k"
      restart: unless-stopped
  organizr_dashboard:
    container_name: organizr_dashboard
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/docker/organizr/config:/config
    ports:
      - 80:80
    image: organizr/organizr
